#' MG2 Demo Data: Sierra Leone Malaria
#'
#' Raw API-style data for 5 malaria data elements from the Sierra Leone DHIS2
#' demo instance. The format matches the output of [api_data()]: one row per
#' facility × data element × month, with a `SUM` (reported value) and `COUNT`
#' (number of reporting sub-units).
#'
#' The dataset covers 60 months: 12 real months (Jan–Dec 2025) downloaded from
#' the demo instance plus 48 months of prior history generated by a seasonal
#' bootstrap. The bootstrap tiles the 12 real months backward four times with:
#' \itemize{
#'   \item Higher facility-level lognormal noise (SD ≈ 35%).
#'   \item Element-specific year-on-year trends — ACT treatment shows a step
#'     increase from 2023 (treatment programme scale-up); inpatient cases and
#'     deaths decline; RDT testing grows gradually.
#'   \item Reporting completeness gaps in earlier years (~65% of facility-months
#'     present in 2021, rising to ~93% by 2024) for the three outpatient
#'     elements, simulating a maturing reporting system.
#'   \item An outlier cluster in RDT-positive values (Jun–Aug 2022): ~5% of
#'     facilities report 3–4× their expected value, leaving signals for the
#'     Outliers tab to detect.
#' }
#' The raw 12-month real data are stored separately in `mg2_demo_raw`.
#'
#' @format A data frame with columns:
#' \describe{
#'   \item{dataElement}{DHIS2 data element UID (character).}
#'   \item{period}{DHIS2 monthly period code, e.g. `"202301"` (character).}
#'   \item{orgUnit}{DHIS2 org unit UID (character).}
#'   \item{categoryOptionCombo}{Category option combo UID, or `NA` for
#'     elements with a single (default) category (character).}
#'   \item{COUNT}{Number of facilities that reported a value (integer).}
#'   \item{SUM}{Sum of reported values across reporting facilities (numeric).}
#' }
#'
#' @details
#' **Data elements included:**
#' \tabular{ll}{
#'   `p4K11MFEWtw` \tab Inpatient malaria cases \cr
#'   `wWy5TE9cQ0V` \tab Inpatient malaria deaths \cr
#'   `wZwzzRnr9N4` \tab RDT positive \cr
#'   `Qk9nnX0i7lZ` \tab RDT negative / tested \cr
#'   `AFM5H0wNq3t` \tab Malaria treated at PHU with ACT < 24 hrs new \cr
#' }
#'
#' **Source:** Sierra Leone DHIS2 demo instance
#' (`https://play.im.dhis2.org/stable-2-41-8/`).
#' Real data are public. Bootstrapped history is synthetic.
#'
#' **Regeneration:** Run `data-raw/generate_demo.R` with a live connection
#' to the demo instance.
#'
#' @seealso `mg2_demo_formula`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo)
#' \dontrun{
#' head(mg2_demo)
#' dplyr::n_distinct(mg2_demo$orgUnit)   # number of facilities
#' dplyr::n_distinct(mg2_demo$period)    # number of months
#' }
"mg2_demo"


#' MG2 Demo Raw Data: Real Sierra Leone Data (12 months)
#'
#' The raw 12 months of real data downloaded from the Sierra Leone DHIS2 demo
#' instance (Jan–Dec 2025). Same format as [mg2_demo] and [api_data()] output.
#' Use this to inspect the true seasonal pattern before the bootstrap is applied,
#' or as a starting point for regenerating the demo with different parameters.
#'
#' @format A data frame with the same columns as `mg2_demo`:
#' `dataElement`, `orgUnit`, `period`, `COUNT`, `SUM`.
#'
#' @seealso `mg2_demo`, `mg2_demo_formula`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo_raw)
#' \dontrun{
#' # Monthly national totals for the real year
#' dplyr::summarise(dplyr::group_by(mg2_demo_raw, dataElement, period),
#'                  total = sum(SUM, na.rm = TRUE))
#' }
"mg2_demo_raw"


#' MG2 Demo Formula Elements
#'
#' Formula elements table for the 6 Sierra Leone malaria data elements shipped
#' in `mg2_demo`. The format matches the `updated_formula_elements$df` reactive
#' produced by the Formula widget: one row per data element × category option
#' combo, with human-readable names and UIDs.
#'
#' @format A data frame with columns:
#' \describe{
#'   \item{Formula.Name}{Formula label (character). All rows use
#'     `"Sierra Leone Malaria"`.}
#'   \item{dataElement}{Human-readable data element name (character).}
#'   \item{Categories}{Category option combo name (character).}
#'   \item{dataElement.id}{DHIS2 data element UID (character).}
#'   \item{categoryOptionCombo.ids}{Category option combo UID (character).}
#'   \item{n_categoryOptions}{Number of category options for this combo
#'     (integer).}
#'   \item{categoryCombo}{Category combo name (character).}
#'   \item{categoryCombo.id}{Category combo UID (character).}
#' }
#' Additional columns from the data element dictionary are included: data set,
#' period type, display name, etc.
#'
#' @seealso `mg2_demo`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo_formula)
#' \dontrun{
#' mg2_demo_formula[, c("dataElement", "Categories", "Formula.Name")]
#' }
"mg2_demo_formula"


#' MG2 Demo Metadata
#'
#' Metadata list for the Sierra Leone DHIS2 demo instance, structured to match
#' the `metadata_YYYY-MM-DD.rds` files saved by the Metadata widget. Pass this
#' object to MG2 functions that accept a `metadata` argument, or load it into
#' the app via the Setup → Directory tab when running in standalone mode.
#'
#' @format A named list with the following elements:
#' \describe{
#'   \item{systemInfo}{DHIS2 system information (list).}
#'   \item{meta_variables}{Distinct data element × category combinations
#'     (data frame).}
#'   \item{orgUnitLevels}{Admin level names and numbers (data frame).}
#'   \item{orgUnits}{Flat org unit table with parent IDs (data frame).}
#'   \item{dataElementDictionary}{Full data element dictionary with category
#'     information (data frame).}
#'   \item{indicatorDictionary}{Indicator table (data frame).}
#'   \item{dataSets.}{Data sets with expanded data set elements (data frame). Note: the trailing dot is part of the name.}
#'   \item{dataSets}{Raw data sets table (data frame).}
#'   \item{categories}{Category option combo summary table (data frame).}
#'   \item{dataElementGroups}{Data element group memberships (data frame).}
#'   \item{ousTree}{Wide-format org unit hierarchy from [ous_tree()] (tibble).}
#'   \item{geoFeatures}{Geographic features for district-level mapping (list
#'     or `NULL` if unavailable).}
#'   \item{validationRules}{DHIS2 validation rules (data frame or empty
#'     tibble).}
#'   \item{resources}{API resource index (data frame or empty tibble).}
#' }
#'
#' @seealso `mg2_demo`, `mg2_demo_formula`, [ous_tree()]
#' @examples
#' data(mg2_demo_meta)
#' names(mg2_demo_meta)
"mg2_demo_meta"


#' MG2 Demo Processed Dataset
#'
#' The Sierra Leone malaria demo data pre-processed through [data_1()]:
#' a `tsibble` with org unit hierarchy joined, data element labels resolved,
#' and time index built. This is the format expected by all downstream MG2
#' analysis functions (DQA, Reporting, Outliers, Evaluation).
#'
#' Shipped pre-built so that [mg2_demo_setup()] can write it to disk
#' instantly without re-running the pipeline.
#'
#' @format A `tsibble` with columns:
#' \describe{
#'   \item{orgUnit}{DHIS2 org unit UID (character).}
#'   \item{dataElement}{Data element name (character).}
#'   \item{dataSet}{Dataset name (character).}
#'   \item{orgUnitName}{Facility name (character).}
#'   \item{level}{Admin level integer (integer).}
#'   \item{National, District, Chiefdom, Facility}{Org unit path at each
#'     admin level (character).}
#'   \item{effectiveLeaf}{Logical; `TRUE` when this row is the lowest
#'     reporting unit (no children reported the same element).}
#'   \item{Month}{`yearmonth` index (tsibble key dimension).}
#'   \item{data}{Display label combining element and category (character).}
#'   \item{data.id}{Internal element × category identifier (character).}
#'   \item{original}{Raw reported value (numeric).}
#'   \item{value}{Logical; `TRUE` when a non-missing value was reported.}
#' }
#'
#' @seealso `mg2_demo`, `mg2_demo_formula`, `mg2_demo_meta`,
#'   [mg2_demo_setup()], [data_1()]
#' @examples
#' data(mg2_demo_processed)
#' \dontrun{
#' tsibble::n_keys(mg2_demo_processed)   # number of facility × element series
#' }
"mg2_demo_processed"
