#' MG2 Demo Data: Sierra Leone Malaria
#'
#' Raw API-style data for 5 malaria data elements from the Sierra Leone DHIS2
#' demo instance. The format matches the output of [api_data()]: one row per
#' facility × data element × month, with a `SUM` (reported value) and `COUNT`
#' (number of reporting sub-units).
#'
#' The dataset covers 72 months: 12 real months (Jan–Dec 2025) downloaded from
#' the demo instance plus 60 months of prior history generated by a seasonal
#' bootstrap. The bootstrap tiles the 12 real months backward five times with:
#' \itemize{
#'   \item Higher facility-level lognormal noise (SD ≈ 35%).
#'   \item Element-specific year-on-year trends — ACT treatment shows a step
#'     increase from 2023 (treatment programme scale-up); inpatient cases and
#'     deaths decline; RDT testing grows gradually.
#'   \item Reporting completeness gaps in earlier years (~65% of facility-months
#'     present in 2020, rising to ~93% by 2024) for the three outpatient
#'     elements, simulating a maturing reporting system.
#'   \item An outlier cluster in RDT-positive values (Jun–Aug 2022): ~5% of
#'     facilities report 3–4× their expected value, leaving signals for the
#'     Outliers tab to detect.
#'   \item A 2025 malaria-reduction pattern: inpatient cases, deaths, RDT
#'     positive, and ACT treated are reduced ~15% (more so in peak-season
#'     months); RDT negative increases ~15% (more in peak season), simulating
#'     an intervention effect the Evaluation tab can detect.
#' }
#' The all-levels processed dataset is stored in `mg2_demo_alllevels`.
#'
#' @format A data frame with columns:
#' \describe{
#'   \item{dataElement}{DHIS2 data element UID (character).}
#'   \item{period}{DHIS2 monthly period code, e.g. `"202301"` (character).}
#'   \item{orgUnit}{DHIS2 org unit UID (character).}
#'   \item{COUNT}{Number of facilities that reported a value (integer).}
#'   \item{SUM}{Sum of reported values across reporting facilities (numeric).}
#' }
#'
#' @details
#' **Data elements included:**
#' \tabular{ll}{
#'   `p4K11MFEWtw` \tab Inpatient malaria cases \cr
#'   `wWy5TE9cQ0V` \tab Inpatient malaria deaths \cr
#'   `wZwzzRnr9N4` \tab RDT positive \cr
#'   `Qk9nnX0i7lZ` \tab RDT negative \cr
#'   `AFM5H0wNq3t` \tab Malaria treated at PHU with ACT < 24 hrs new \cr
#' }
#'
#' **Source:** Sierra Leone DHIS2 demo instance
#' (`https://play.im.dhis2.org/stable-2-41-8/`).
#' Real data are public. Bootstrapped history is synthetic.
#'
#' **Regeneration:** Run `data-raw/generate_demo.R` with a live connection
#' to the demo instance.
#'
#' @seealso `mg2_demo_formula`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo)
#' \dontrun{
#' head(mg2_demo)
#' dplyr::n_distinct(mg2_demo$orgUnit)   # number of facilities
#' dplyr::n_distinct(mg2_demo$period)    # number of months
#' }
"mg2_demo"


#' MG2 Demo All-Levels Dataset: Sierra Leone Malaria (3 years)
#'
#' Processed Sierra Leone malaria dataset covering all organisational unit
#' levels (national, district, chiefdom, facility) for 50 data elements over
#' approximately 3 years. Includes outlier flags and all columns produced by
#' the MG2 processing pipeline. Written to disk by [mg2_demo_setup()].
#'
#' @format A data.table / data frame with columns including:
#' `orgUnit`, `orgUnitName`, `level`, `National`, `District`, `Chiefdom`,
#' `Facility`, `dataSet`, `dataElement`, `Month`, `data`, `data.id`,
#' `original`, `value`, and outlier flag columns
#' (`key_entry_error`, `over_max`, `mad15`, `mad10`, `mad5`,
#' `seasonal5`, `seasonal3`, `expected`).
#'
#' @seealso `mg2_demo`, `mg2_demo_processed`, `mg2_demo_formula`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo_alllevels)
#' \dontrun{
#' dplyr::n_distinct(mg2_demo_alllevels$orgUnit)   # all org unit levels
#' dplyr::n_distinct(mg2_demo_alllevels$data.id)   # number of data elements
#' }
"mg2_demo_alllevels"


#' MG2 Demo Formula Elements
#'
#' Formula elements table for the 6 Sierra Leone malaria data elements shipped
#' in `mg2_demo`. The format matches the `updated_formula_elements$df` reactive
#' produced by the Formula widget: one row per data element × category option
#' combo, with human-readable names and UIDs.
#'
#' @format A data frame with columns:
#' \describe{
#'   \item{Formula.Name}{Formula label (character). All rows use
#'     `"Sierra Leone Malaria Demo"`.}
#'   \item{role}{Element role: `"primary"` for ACT treatment; `"secondary"`
#'     for all others (character).}
#'   \item{dataElement}{Human-readable data element name (character).}
#'   \item{Categories}{Category option combo name (character).}
#'   \item{dataElement.id}{DHIS2 data element UID (character).}
#'   \item{categoryOptionCombo.ids}{Category option combo UID (character).}
#'   \item{n_categoryOptions}{Number of category options for this combo (integer).}
#'   \item{categoryCombo}{Category combo name (character).}
#'   \item{categoryCombo.id}{Category combo UID (character).}
#'   \item{dataSet}{Data set name (character).}
#'   \item{dataSet.ids}{Data set UID (character).}
#'   \item{dataElementGroup}{Data element group name (character).}
#'   \item{dataElementGroups.id}{Data element group UID (character).}
#'   \item{displayName}{DHIS2 display name (character).}
#'   \item{displayShortName}{DHIS2 display short name (character).}
#'   \item{shortName}{Short name (character).}
#'   \item{periodType}{DHIS2 period type, e.g. `"Monthly"` (character).}
#'   \item{zeroIsSignificant}{Logical; whether zero values are meaningful.}
#' }
#'
#' @seealso `mg2_demo`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo_formula)
#' \dontrun{
#' mg2_demo_formula[, c("dataElement", "Categories", "Formula.Name")]
#' }
"mg2_demo_formula"


#' MG2 Demo Metadata
#'
#' Metadata list for the Sierra Leone DHIS2 demo instance, structured to match
#' the `metadata_YYYY-MM-DD.rds` files saved by the Metadata widget. Pass this
#' object to MG2 functions that accept a `metadata` argument, or load it into
#' the app via the Setup → Directory tab when running in standalone mode.
#'
#' @format A named list with the following elements:
#' \describe{
#'   \item{systemInfo}{DHIS2 system information (list).}
#'   \item{meta_variables}{Distinct data element × category combinations
#'     (data frame).}
#'   \item{orgUnitLevels}{Admin level names and numbers (data frame).}
#'   \item{orgUnits}{Flat org unit table with parent IDs (data frame).}
#'   \item{dataElementDictionary}{Full data element dictionary with category
#'     information (data frame).}
#'   \item{indicatorDictionary}{Indicator table (data frame).}
#'   \item{dataSets.}{Data sets with expanded data set elements (data frame). Note: the trailing dot is part of the name.}
#'   \item{dataSets}{Raw data sets table (data frame).}
#'   \item{categories}{Category option combo summary table (data frame).}
#'   \item{dataElementGroups}{Data element group memberships (data frame).}
#'   \item{ousTree}{Wide-format org unit hierarchy from [ous_tree()] (tibble).}
#'   \item{geoFeatures}{Geographic features for district-level mapping (list
#'     or `NULL` if unavailable).}
#'   \item{validationRules}{DHIS2 validation rules (data frame or empty
#'     tibble).}
#'   \item{resources}{API resource index (data frame or empty tibble).}
#' }
#'
#' @seealso `mg2_demo`, `mg2_demo_formula`, [ous_tree()]
#' @examples
#' data(mg2_demo_meta)
#' names(mg2_demo_meta)
"mg2_demo_meta"


#' MG2 Demo Processed Dataset
#'
#' The Sierra Leone malaria demo data pre-processed through [data_1()]:
#' a `tsibble` with org unit hierarchy joined, data element labels resolved,
#' and time index built. This is the format expected by all downstream MG2
#' analysis functions (DQA, Reporting, Outliers, Evaluation).
#'
#' Shipped pre-built so that [mg2_demo_setup()] can write it to disk
#' instantly without re-running the pipeline.
#'
#' @format A `tsibble` with columns:
#' \describe{
#'   \item{orgUnit}{DHIS2 org unit UID (character).}
#'   \item{dataElement}{Data element name (character).}
#'   \item{dataSet}{Dataset name (character).}
#'   \item{orgUnitName}{Facility name (character).}
#'   \item{level}{Admin level integer (integer).}
#'   \item{National, District, Chiefdom, Facility}{Org unit path at each
#'     admin level (character).}
#'   \item{effectiveLeaf}{Logical; `TRUE` when this row is the lowest
#'     reporting unit (no children reported the same element).}
#'   \item{Month}{`yearmonth` index (tsibble key dimension).}
#'   \item{data}{Display label combining element and category (character).}
#'   \item{data.id}{Internal element × category identifier (character).}
#'   \item{original}{Raw reported value (numeric).}
#'   \item{value}{Logical; `TRUE` when a non-missing value was reported.}
#' }
#'
#' @seealso `mg2_demo`, `mg2_demo_formula`, `mg2_demo_meta`,
#'   [mg2_demo_setup()], [data_1()]
#' @examples
#' data(mg2_demo_processed)
#' \dontrun{
#' tsibble::n_keys(mg2_demo_processed)   # number of facility × element series
#' }
"mg2_demo_processed"


#' Sierra Leone District Polygons (Demo Geography)
#'
#' An `sf` object containing district-level polygon boundaries for Sierra Leone,
#' formatted to match the `geoFeatures` structure expected by MG2's metadata
#' widget. Included so the DQA map, Climate widget, and Burden map all render
#' correctly when using the Sierra Leone demo data.
#'
#' Source: GADM level-2 polygons via \pkg{geodata}, with "Western Rural" and
#' "Western Urban" merged into "Western Area" to match the DHIS2 district
#' naming used in \code{mg2_demo_alllevels}.
#'
#' @format An `sf` data frame with 13 rows (one per district) and columns:
#' \describe{
#'   \item{id}{Placeholder identifier (character).}
#'   \item{name}{District name — matches the `District` column in
#'     \code{mg2_demo_alllevels} and the `name` field used by map joins.}
#'   \item{level}{Admin level — always \code{2L} (district).}
#'   \item{levelName}{Human-readable level label: \code{"District"}.}
#'   \item{parentName}{Parent admin unit: \code{"Sierra Leone"}.}
#'   \item{geometry}{Multipolygon geometry in WGS84 (EPSG:4326).}
#' }
#' @seealso [mg2_demo_setup()]
#' @source \url{https://geodata.ucdavis.edu/gadm/} (GADM 4.1, CC BY 4.0)
"mg2_demo_geo"
