#' MG2 Demo Data: Sierra Leone Malaria
#'
#' Raw API-style data for 6 malaria data elements from the Sierra Leone DHIS2
#' demo instance. The format matches the output of [api_data()]: one row per
#' facility × data element × category option combo × month, with a `SUM`
#' (reported value) and `COUNT` (number of facilities that reported).
#'
#' The dataset covers 60 months: 12 real months downloaded from the demo
#' instance plus 48 months of prior history generated by a seasonal bootstrap
#' (tile the real 12 months four times with lognormal multiplicative noise,
#' SD ≈ 12%). This gives enough history for time-series modelling and
#' intervention analysis without requiring a live server connection.
#'
#' @format A data frame with columns:
#' \describe{
#'   \item{dataElement}{DHIS2 data element UID (character).}
#'   \item{period}{DHIS2 monthly period code, e.g. `"202301"` (character).}
#'   \item{orgUnit}{DHIS2 org unit UID (character).}
#'   \item{categoryOptionCombo}{Category option combo UID, or `NA` for
#'     elements with a single (default) category (character).}
#'   \item{COUNT}{Number of facilities that reported a value (integer).}
#'   \item{SUM}{Sum of reported values across reporting facilities (numeric).}
#' }
#'
#' @details
#' **Data elements included:**
#' \tabular{ll}{
#'   `TV5zBFFkZLu` \tab Malaria cases confirmed \cr
#'   `p4K11MFEWtw` \tab Inpatient malaria cases \cr
#'   `wWy5TE9cQ0V` \tab Inpatient malaria deaths \cr
#'   `wZwzzRnr9N4` \tab RDT positive \cr
#'   `Qk9nnX0i7lZ` \tab RDT negative / tested \cr
#'   `AFM5H0wNq3t` \tab Malaria treated at PHU with ACT < 24 hrs new \cr
#' }
#'
#' **Source:** Sierra Leone DHIS2 demo instance
#' (`https://play.im.dhis2.org/stable-2-42-4/`).
#' Real data are public. Bootstrapped history is synthetic.
#'
#' **Regeneration:** Run `data-raw/generate_demo.R` with a live connection
#' to the demo instance.
#'
#' @seealso `mg2_demo_formula`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo)
#' \dontrun{
#' head(mg2_demo)
#' dplyr::n_distinct(mg2_demo$orgUnit)   # number of facilities
#' dplyr::n_distinct(mg2_demo$period)    # number of months
#' }
"mg2_demo"


#' MG2 Demo Formula Elements
#'
#' Formula elements table for the 6 Sierra Leone malaria data elements shipped
#' in `mg2_demo`. The format matches the `updated_formula_elements$df` reactive
#' produced by the Formula widget: one row per data element × category option
#' combo, with human-readable names and UIDs.
#'
#' @format A data frame with columns:
#' \describe{
#'   \item{Formula.Name}{Formula label (character). All rows use
#'     `"Sierra Leone Malaria"`.}
#'   \item{dataElement}{Human-readable data element name (character).}
#'   \item{Categories}{Category option combo name (character).}
#'   \item{dataElement.id}{DHIS2 data element UID (character).}
#'   \item{categoryOptionCombo.ids}{Category option combo UID (character).}
#'   \item{n_categoryOptions}{Number of category options for this combo
#'     (integer).}
#'   \item{categoryCombo}{Category combo name (character).}
#'   \item{categoryCombo.id}{Category combo UID (character).}
#' }
#' Additional columns from the data element dictionary are included: data set,
#' period type, display name, etc.
#'
#' @seealso `mg2_demo`, `mg2_demo_meta`
#' @examples
#' data(mg2_demo_formula)
#' \dontrun{
#' mg2_demo_formula[, c("dataElement", "Categories", "Formula.Name")]
#' }
"mg2_demo_formula"


#' MG2 Demo Metadata
#'
#' Metadata list for the Sierra Leone DHIS2 demo instance, structured to match
#' the `metadata_YYYY-MM-DD.rds` files saved by the Metadata widget. Pass this
#' object to MG2 functions that accept a `metadata` argument, or load it into
#' the app via the Setup → Directory tab when running in standalone mode.
#'
#' @format A named list with the following elements:
#' \describe{
#'   \item{systemInfo}{DHIS2 system information (list).}
#'   \item{meta_variables}{Distinct data element × category combinations
#'     (data frame).}
#'   \item{orgUnitLevels}{Admin level names and numbers (data frame).}
#'   \item{orgUnits}{Flat org unit table with parent IDs (data frame).}
#'   \item{dataElementDictionary}{Full data element dictionary with category
#'     information (data frame).}
#'   \item{indicatorDictionary}{Indicator table (data frame).}
#'   \item{dataSets.}{Data sets with expanded data set elements (data frame). Note: the trailing dot is part of the name.}
#'   \item{dataSets}{Raw data sets table (data frame).}
#'   \item{categories}{Category option combo summary table (data frame).}
#'   \item{dataElementGroups}{Data element group memberships (data frame).}
#'   \item{ousTree}{Wide-format org unit hierarchy from [ous_tree()] (tibble).}
#'   \item{geoFeatures}{Geographic features for district-level mapping (list
#'     or `NULL` if unavailable).}
#'   \item{validationRules}{DHIS2 validation rules (data frame or empty
#'     tibble).}
#'   \item{resources}{API resource index (data frame or empty tibble).}
#' }
#'
#' @seealso `mg2_demo`, `mg2_demo_formula`, [ous_tree()]
#' @examples
#' data(mg2_demo_meta)
#' names(mg2_demo_meta)
"mg2_demo_meta"
